// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/store-themes/DarkLuxury.tsx": () => import("../components/mockups/store-themes/DarkLuxury.tsx"),
  "./components/mockups/store-themes/StarkMono.tsx": () => import("../components/mockups/store-themes/StarkMono.tsx"),
  "./components/mockups/store-themes/VibrantModern.tsx": () => import("../components/mockups/store-themes/VibrantModern.tsx")
};
